Sprint 1/step 2
Vetl-off0098/react-burger pull request #1
Opened 2023-07-23 19:52 UTC by Vetl-off0098

По техническим причинам ветка main не может принимать участие в Pull Request, поэтому ее роль на себя возьмёт ветка master (как и в других нормальных сервисах по работе с  системами контроля версий).

2023-07-23 21:03 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть отписка от слушателя событий
- Проект соответствует макету
- Реализовали механизм добавления в конструктор
- Хорошая работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку ответа сервера
- Добавьте isRequired там где его не хватает
- во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать
- вынесите магическое значение 27 в именованную константу const ECK_KEYCODE = 27

**Можно лучше**
Элементы хедера должны быть ссылками, а не просто текстом. Сейчас можно использовать просто тег `<a/>`.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/app-header/button-header/button-header.jsx
> +  children: PropTypes.any
**Можно лучше**
Тут больше подходит тип `node`

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/app/App.jsx
> +    fetch(api)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/app/App.jsx
> +      .then(data => data.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/app/App.jsx
> +        console.error(e);
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const totalPrice = props.burger.burgerMain.reduce((acc, cur) => {
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    <section className={styles.constructorAndButton}>
**Можно лучше**
тег section не стоит употреблять слишком часто, он не является заменой тегу `div` и если он вам нужен только для стилизации, то лучше использовать `div` 
Перечень случаев когда стоит использовать section приведены в доке  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +const itemsPropTypes = PropTypes.shape({
**Необходимо исправить**
- После закрывающей скобки функции shape и у каждого поля объекта так же необходимо ставить `isRequired`

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +  info: PropTypes.shape({
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +    if (keyPress.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2023-07-23 21:03 UTC, andryxxa93 commented on src/utils/data.js
> +const productData = [
**Можно лучше**
файл больше не пригодится - его можно удалить

2023-07-23 21:03 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.removeEventListener('keydown', closeModal);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-07-24 19:29 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +    fetch(api)
Если честно, то не представляю как это будет выглядеть. В проверке ответа присутствуют вызовы setState, которые придется пробрасывать в utils/burger-api.js как параметры?

![image](https://github.com/Vetl-off0098/react-burger/assets/45787970/f58f85d8-7f83-4078-9b6c-b75effcb67d3)

2023-07-24 19:45 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +      .then(data => data.json())
Вопрос... А Promise в функции checkReponse доступен ли?

2023-07-24 19:57 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +        console.error(e);
React вроде не поддерживает многоуровненовое ветвление, как например во Vue (v-if, v-else-if, v-else).
Как это можно сделать, если, например, в компоненте будет еще одна переменная noData?
И как из ошибки е получить понятный пользователю ответ?

![image](https://github.com/Vetl-off0098/react-burger/assets/45787970/437d1fb9-c2a4-429b-81f5-2acd2198f9e0)

2023-07-24 20:14 UTC, Vetl-off0098 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const totalPrice = props.burger.burgerMain.reduce((acc, cur) => {
Не знал, что объявлять useState нужно ДО useMemo, в котором используется этот state.

То есть вот так будет ошибка 
![image](https://github.com/Vetl-off0098/react-burger/assets/45787970/d7c02b33-d483-456c-a0c4-9869ca4cd7b2)
![image](https://github.com/Vetl-off0098/react-burger/assets/45787970/1f833633-2f96-40dd-90f4-ba404f075f92)

2023-07-24 20:32 UTC, Vetl-off0098 commented on src/components/ingredient-details/ingredient-details.jsx
> +  info: PropTypes.shape({
На поле _v ругается, поэтому его не стал помечать как обязательное

2023-07-24 20:40 UTC, Vetl-off0098 commented
По некоторым советам по улучшению есть вопросы, а все необходимые для сдачи правки внес и запушил

2023-07-25 13:11 UTC, andryxxa93 commented on src/components/app/App.jsx
> +    fetch(api)
Если говорить об этом примере, то можно сделать следующим образом

  ```
const [ingredientsLoading, setIngredientsLoading] = useState(true);

  const getData = async () => {
    try {
      const data = await getIngredients();
      setIngredients(data)
    } catch (e) {
      console.log(e);
    }
    setIngredientsLoading(false)
  }
```

2023-07-25 13:17 UTC, andryxxa93 commented on src/components/app/App.jsx
> +        console.error(e);
Просто не нужно делать это по принципу if-else.
Вам всё равно нужно вернуть что-то одно, или лоадер, или сообщение об ошибке или основной контент. Всё это легко достигается благодаря условному рендерингу или через обычный return до основной верстки.
Насчет сообщения пользователю можно просто показывать модальное окно - "что-то пошло не так, попробуйте зайти позже". 

```
if (error) {
return (...)
}


return (
  <>{основной контент}</>
)
```

2023-07-25 13:18 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-25 13:19 UTC, andryxxa93 commented on src/components/app/App.jsx
> +      .then(data => data.json())
А почему он не должен быть доступен? 😊

2023-07-25 15:35 UTC, merged