Добавлен Context
Vetl-off0098/react-burger pull request #2
Opened 2023-08-08 21:07 UTC by Vetl-off0098

2023-08-09 16:41 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- в контекст обернуты только те компоненты, что будут его использовать
- есть проверка успешности запроса 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- у вас переменная которую вы передаёте в контекст называется иначе, нежели та, что вы из контекста достаете
- данные передавать нужно только через контекст в файле app.jsx

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
> +  // function reducer(state, action) {
**Можно улучшить**
Ненужный код лучше удалять

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
>              <BurgerIngredients items={items} pushIngredient={pushIngredient}/>
**можно лучше**
На данном этапе уже можно передать ингредиенты черных контекст

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
**можно лучше**
Использовать числительные в именовании переменных - плохая практика. Это усложняет восприятие и расширение кода

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
> +  // const checkResponse = (res) => {
**Можно улучшить**
Ненужный код лучше удалять

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
**необходимо исправить** 
Вы передаёте данные и через контекст и через пропсы. Надо только через контекст

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
**необходимо исправить**
Переменная у вас называется burger1, а достаете вы в компоненте переменную burger

2023-08-09 16:41 UTC, andryxxa93 commented on src/components/burger-constructor/final-block/final-block.jsx
> +      .catch(e => {
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-08-11 14:48 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +  // function reducer(state, action) {
А это заготовка для будущего вопроса )

2023-08-11 15:34 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
Исправил

2023-08-11 15:34 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +  // const checkResponse = (res) => {
Исправил

2023-08-11 15:34 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
Исправил

2023-08-11 15:34 UTC, Vetl-off0098 commented on src/components/app/App.jsx
> +              <BurgerConstructor burger={burger1} deleteIngredient={deleteIngredient}/>
Исправил

2023-08-11 15:47 UTC, Vetl-off0098 commented
Еще реализован функционал по добавлению ингредиентов в бургер (по нажатию на картинку игредиента в карточке ингредиента) и удаление их. Синхронизируется кол-во ингредиентов в бургере и их каунт в списке ингредиентов. Учтена логика изменения булки, так как удалить ее, либо добавить еще одну мы не можем. При нажатии на кнопку "Оформить заказ" отсылается запрос с айдишниками выбранных ингредиентов и полученный номер заказа выводится в модальном окне.

2023-08-12 07:19 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-13 12:53 UTC, merged