Sprint 5/step 1
Vetl-off0098/react-burger pull request #6
Opened 2023-11-22 13:10 UTC by Vetl-off0098

2023-11-22 14:13 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Реализован универсальный веб-сокет
- Хорошая типизация проекта
- Сокеты открываются и закрываются согласно брифу

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Проект собирается с ошибкой ts
<img width="1440" alt="image" src="https://github.com/Vetl-off0098/react-burger/assets/60173362/38635558-de60-40e0-b47c-ccf50a7c700c">

- В проекте много any. От части из них можно без проблем избавиться

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-22 14:13 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.ts
> +          dispatch({type: onMessage, payload: {data: parsedData, timestamp: new Date().getTime() / 100}})
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-11-22 14:13 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.ts
> +      if (wsClose && type === wsClose && socket) {
Можно лучше
Так как браузерный веб-сокет не обладает возможностью переподключения из-за обрыва соединения - желательно это делать самому через setTiimeout

2023-11-22 14:13 UTC, andryxxa93 commented on src/services/reducers/feedReducer.ts
> +  orders: any[],
**Необходимо исправить**
Избавьтесь от `any` в данном месте

2023-11-23 15:43 UTC, Vetl-off0098 commented on src/services/middleware/socketMiddleware.ts
> +          dispatch({type: onMessage, payload: {data: parsedData, timestamp: new Date().getTime() / 100}})
Исправил

2023-11-23 15:43 UTC, Vetl-off0098 commented on src/services/middleware/socketMiddleware.ts
> +      if (wsClose && type === wsClose && socket) {
Исправил

2023-11-23 15:43 UTC, Vetl-off0098 commented on src/services/reducers/feedReducer.ts
> +  orders: any[],
Исправил

2023-11-23 15:45 UTC, Vetl-off0098 commented
То, что касается ошибки типизации, то у меня ничего не высвечивается. Вслепую чутка изменил тип otherIngrs, надеюсь поможет.

2023-11-24 10:11 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-24 14:19 UTC, merged